### ISSUE TITLE
borevent files: have wrong content

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11188] opened 2024-07-16 03:03 UTC
- [ ] on amoy: i did re-generated borevent files from scratch and it can't pass execution (around block 8684176). But execution works if enable fallback to remote heimdall in next 2 cases: `if len(events) == 50 || len(events) == 0 {` (enabling only for `50` doesn't work in this case: see also https://github.com/ledgerwatch/erigon/issues/10310  . What i know: if remove recent borevent files - sync will work (it means data in DB seems are good - and bug in in files production. or maybe just race/corner_case).

- [ ] we need verification command for borevent files: https://github.com/ledgerwatch/erigon/pull/9436
- [ ] also bor main net around block 48 mil as per https://github.com/erigontech/erigon/issues/10886

**Comment by mh0lt** [comment] 2024-08-19 10:14
In this PR: https://github.com/erigontech/erigon/pull/9436 this extra code has been removed.

So far it has been texted on amoy and is currently being tested on bor-mainnet.

For now I'm assuming the issue is resolved - hence closing this issue. It can be re-opened if the underlying cause has not been fixed by the PR.

**Closed by mh0lt** 2024-08-19 10:14 UTC
Labels: polygon, priority:high, complexity:medium
