### ISSUE TITLE
Reward traces missing on trace_block RPC call in erigon 3.0.0-alpha5

### ISSUE THREAD

**Issue by soad003** [erigontech/erigon#12561] opened 2024-10-31 14:12 UTC
#### System information

Erigon version: erigon:v3.0.0-alpha5 && erigon:v2.60.2

OS & Version: Linux

Chain/Network: Eth Mainnet

#### Expected behaviour

Erigon 3 and 2 return the same data when trace_block is called.

#### Actual behaviour

Erigon 3 output misses the reward trace of the block.

#### Steps to reproduce the behaviour

```
> curl -X POST http://erigon2.60 -H 'Content-Type: application/json' -d '{"method":"trace_block","params":["21030000", false],"id":1,"jsonrpc":"2.0"}' | jq > old.txt

> curl -X POST http://erigon3.0 -H 'Content-Type: application/json' -d '{"method":"trace_block","params":["21030000", false],"id":1,"jsonrpc":"2.0"}' | jq > new.txt

> diff old.txt new.txt 
<     },
<     {
<       "action": {
<         "author": "0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97",
<         "rewardType": "block",
<         "value": "0x1bc16d674ec80000"
<       },
<       "blockHash": "0x555b417f4a74ac16f83079dec88087318575aa292f1212259862d446bada0f3b",
<       "blockNumber": 21030000,
<       "result": null,
<       "subtraces": 0,
<       "traceAddress": [],
<       "type": "reward"

```

**Comment by yperbasis** [comment] 2024-11-08 10:44
Block rewards are no longer awarded after the Merge. Which erigon 2 version did you use? The latest one (v2.60.10) doesn't output block rewards either.

**Comment by soad003** [comment] 2024-11-08 17:50
@yperbasis we used v2.60.2 before, just tested with v2.60.10 (docker), still get reward traces. I will do some more debugging on monday.

**Comment by mdragaschnig** [comment] 2024-11-14 15:54
I have the same issue, using the official 2.60.10 image

```
erigontech/erigon   v2.60.10   c2ee3624690f   8 days ago   597MB

 git_branch=release/2.60 git_tag=v2.60.9-4-g3afee08bff
```

includes the reward trace of the block

```
 curl -X POST http://client-server:8545 -H 'Content-Type: application/json' -d '{"method":"trace_block","params":["21030000", false],"id":1,"jsonrpc":"2.0"}' | jq | tail -n 15
 
    {
      "action": {
        "author": "0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97",
        "rewardType": "block",
        "value": "0x1bc16d674ec80000"
      },
      "blockHash": "0x555b417f4a74ac16f83079dec88087318575aa292f1212259862d446bada0f3b",
      "blockNumber": 21030000,
      "result": null,
      "subtraces": 0,
      "traceAddress": [],
      "type": "reward"
    }
  ]
}
```

**Comment by yperbasis** [comment] 2024-11-21 13:26
Sorry, I can't reproduce the issue and am out of ideas, so closing.

**Closed by yperbasis** 2024-11-21 13:26 UTC
Labels: imp1, erigon3

**Comment by mdragaschnig** [comment] 2024-11-25 15:06
> Sorry, I can't reproduce the issue and am out of ideas, so closing.

Again, thanks for testing! 
I've tested with the latest 2.x docker image [v2.61.0-beta](https://hub.docker.com/layers/erigontech/erigon/v2.61.0-beta1/images/sha256-12734df3179a8a02a684d97d7bfa381fb07b841e7315d827daede9f0d1696921?context=explore) and still see block rewards.

As mentioned in https://github.com/erigontech/erigon/issues/12525#issuecomment-2493401157 , can the problem lie in the database that has been produced with a pre 2.60.10 version?

**Comment by yperbasis** [comment] 2024-11-26 14:25
> Again, thanks for testing! I've tested with the latest 2.x docker image [v2.61.0-beta](https://hub.docker.com/layers/erigontech/erigon/v2.61.0-beta1/images/sha256-12734df3179a8a02a684d97d7bfa381fb07b841e7315d827daede9f0d1696921?context=explore) and still see block rewards.
> 
> As mentioned in [#12525 (comment)](https://github.com/erigontech/erigon/issues/12525#issuecomment-2493401157) , can the problem lie in the database that has been produced with a pre 2.60.10 version?

No, this is a pure code change, not related to the database. That's why I'm a bit lost why v2.60.10 or v2.61.0-beta aren't working for you.
