### ISSUE TITLE
always show this ?[txpool] flush: sender address not found by ID senderID=48733  how to solve this ....

### ISSUE THREAD

**Issue by senkiss** [erigontech/erigon#9817] opened 2024-03-27 06:59 UTC
INFO[03-27|06:56:15.912] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload) 
INFO[03-27|06:56:16.208] RPC Daemon notified of new headers       from=19524034 to=19524035 amount=1 hash=0x54fd6ca21597229151bf32c71ad6522183c7b8801afe86987c314168dacb8c1e header sending=32.985µs log sending=692ns
INFO[03-27|06:56:16.208] head updated                             hash=0x54fd6ca21597229151bf32c71ad6522183c7b8801afe86987c314168dacb8c1e number=19524035
INFO[03-27|06:56:24.837] [NewPayload] Handling new payload        height=19524036 hash=0x9bae8bf247f6f375b30d5d1ec119c8bd2096c6b8d0ff521f823468c462581f1f
INFO[03-27|06:56:25.175] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload) 
INFO[03-27|06:56:25.454] RPC Daemon notified of new headers       from=19524035 to=19524036 amount=1 hash=0x9bae8bf247f6f375b30d5d1ec119c8bd2096c6b8d0ff521f823468c462581f1f header sending=27.815µs log sending=481ns
INFO[03-27|06:56:25.454] head updated                             hash=0x9bae8bf247f6f375b30d5d1ec119c8bd2096c6b8d0ff521f823468c462581f1f number=19524036
WARN[03-27|06:56:29.731] [txpool] flush: sender address not found by ID senderID=48733
WARN[03-27|06:56:29.734] [txpool] flush: sender address not found by ID senderID=69113
INFO[03-27|06:56:37.759] [NewPayload] Handling new payload        height=19524037 hash=0x1fc6b3ae94a00f16dc49144cad1f85e3faacd65947be7025cb1d6efd7b89c94c
INFO[03-27|06:56:38.226] [updateForkchoice] Fork choice update: flushing in-memory state (built by previous newPayload) 
INFO[03-27|06:56:38.509] RPC Daemon notified of new headers       from=19524036 to=19524037 amount=1 hash=0x1fc6b3ae94a00f16dc49144cad1f85e3faacd65947be7025cb1d6efd7b89c94c header sending=20.891µs log sending=651ns
INFO[03-27|06:56:38.509] head updated                             hash=0x1fc6b3ae94a00f16dc49144cad1f85e3faacd65947be7025cb1d6efd7b89c94c number=19524037

**Comment by AskAlexSharov** [comment] 2024-08-14 10:52
duplicate of https://github.com/erigontech/erigon/issues/8045

**Closed by AskAlexSharov** 2024-08-14 10:52 UTC
Labels: priority:medium
