### ISSUE TITLE
e3: bor.go has hack `if len(events) == 50` to fallback to remote Heimdall

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#10310] opened 2024-05-14 03:45 UTC
- To validate/re-generate bor-mainnet event files - because of `bor.go` has hack `if blockNum <= chain.Chain.FrozenBorBlocks() && len(events) == 50 {` to fallback to remote Heimdall and without this hack execution doesn't work (after 46M on bor-mainnet and after 48M on Mumbai). 

- sometime this hack is not enough and need `if blockNum <= chain.Chain.FrozenBorBlocks() && len(events) == 50 || len(events) == 0 {` (but if degradating perf greatly)

**Comment by mh0lt** [comment] 2024-08-19 10:11
In this PR: https://github.com/erigontech/erigon/pull/9436 this extra code has been removed.

So far it has been texted on amoy and is currently being tested on bor-mainnet.

For now I'm assuming the issue is resolved - hence closing this issue.  It can be re-opened if the underlying cause has not been fixed by the PR.

**Closed by mh0lt** 2024-08-19 10:11 UTC
Labels: polygon, priority:high, erigon3, complexity:high
