### ISSUE TITLE
erigon_3.0.0-alpha4  can't sync block

### ISSUE THREAD

**Issue by zhy827827** [erigontech/erigon#12252] opened 2024-10-09 02:06 UTC
erigon_3.0.0-alpha4 doesn't sync the data

[EROR] [10-08|03:42:51.698] Staged Sync err="[7/9 Execution] StateV3.Apply: hash sort failed: loadIntoTable : unfold: Branch failed: storage file not found"
```
Oct 08 03:39:24 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:24.748] [7/9 Execution] Done                     blk=62436676 blks=1003 blk/s=49.8 txs=49055 tx/s=2.43k gas/s=414.52M buf=42.7MB/2.0GB stepsInDB=0.00 step=2940.0 alloc=24.3GB sys=44.3GB
Oct 08 03:39:24 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [EROR] [10-08|03:39:24.748] Staged Sync                              err="[7/9 Execution] StateV3.Apply: hash sort failed: loadIntoTable : unfold: Branch failed: storage file not found"
Oct 08 03:39:25 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:25.301] [7/9 Execution] starting                 from=62435674 to=62446291 fromTxNum=4593769858 offsetFromBlockBeginning=0 initialCycle=true useExternalTx=false
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:45.309] [7/9 Execution]                          blk=62436699 blks=1026 blk/s=51.3 txs=50139 tx/s=2.50k gas/s=425.90M buf=43.3MB/2.0GB stepsInDB=0.95 step=2940.0 alloc=31.6GB sys=44.3GB
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [WARN] [10-08|03:39:45.444] [agg] lookupVisibleFileByItsRange: file not found stepFrom=2936 stepTo=2938 _visible=0-2048;2048-2560;2560-2816;2816-2880;2880-2912;2912-2928;2928-2936;2936-2940; visibleFilesCount=8
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [CRIT] [10-08|03:39:45.444] storage file of steps 2936-2938 not found
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]:
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:45.444] [7/9 Execution] Done                     blk=62436699 blks=1026 blk/s=50.9 txs=50139 tx/s=2.48k gas/s=423.05M buf=43.3MB/2.0GB stepsInDB=0.00 step=2940.0 alloc=31.6GB sys=44.3GB
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [EROR] [10-08|03:39:45.445] Staged Sync                              err="[7/9 Execution] StateV3.Apply: hash sort failed: loadIntoTable : unfold: Branch failed: storage file not found"
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:45.995] [7/9 Execution] starting                 from=62435674 to=62446291 fromTxNum=4593769858 offsetFromBlockBeginning=0 initialCycle=true useExternalTx=false

```

**Comment by taratorio** [comment] 2024-10-10 15:24
duplicate of https://github.com/erigontech/erigon/issues/12208
fix merged in main, currently in testing https://github.com/erigontech/erigon/commit/f24d0922527437634df49376e1fbe82e9e404e6c

**Comment by taratorio** [comment] 2024-10-10 15:26
closing but please re-open if you see it happening again after https://github.com/erigontech/erigon/commit/f24d0922527437634df49376e1fbe82e9e404e6c

**Closed by taratorio** 2024-10-10 15:26 UTC

**Comment by zhy827827** [comment] 2024-10-16 06:10
ubuntu@rockx-mainnet-polygon-archive-mm-02:/opt/rockx/soft/erigon$ journalctl -u erigon.service -f
Oct 16 06:08:06 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [EROR] [10-16|06:08:06.598] Staged Sync                              err="[3/9 BorHeimdall] invalid event record received blockNum=62848864, eventId=2968357 (exp 2968357), chainId=137 (exp 137), time=2024-10-10 02:19:08.483928026 +0000 UTC (exp from 2024-10-10 02:41:37 +0000 UTC, to 2024-10-10 02:42:11 +0000 UTC)"
Oct 16 06:08:07 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:07.362] [3/9 BorHeimdall] Processing spans...    from=9822 to=9831
Oct 16 06:08:07 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:07.389] [3/9 BorHeimdall] Processing sync events... from=62848860 to=62913594
Oct 16 06:08:07 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [EROR] [10-16|06:08:07.439] Staged Sync                              err="[3/9 BorHeimdall] invalid event record received blockNum=62848864, eventId=2968357 (exp 2968357), chainId=137 (exp 137), time=2024-10-10 02:19:08.483928026 +0000 UTC (exp from 2024-10-10 02:41:37 +0000 UTC, to 2024-10-10 02:42:11 +0000 UTC)"
Oct 16 06:08:08 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:08.202] [3/9 BorHeimdall] Processing spans...    from=9822 to=9831
Oct 16 06:08:08 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:08.233] [3/9 BorHeimdall] Processing sync events... from=62848860 to=62913594
Oct 16 06:08:08 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [EROR] [10-16|06:08:08.288] Staged Sync                              err="[3/9 BorHeimdall] invalid event record received blockNum=62848864, eventId=2968357 (exp 2968357), chainId=137 (exp 137), time=2024-10-10 02:19:08.483928026 +0000 UTC (exp from 2024-10-10 02:41:37 +0000 UTC, to 2024-10-10 02:42:11 +0000 UTC)"
Oct 16 06:08:09 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:09.070] [3/9 BorHeimdall] Processing spans...    from=9822 to=9831
Oct 16 06:08:09 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:09.109] [3/9 BorHeimdall] Processing sync events... from=62848860 to=62913594
Oct 16 06:08:09 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [EROR] [10-16|06:08:09.164] Staged Sync                              err="[3/9 BorHeimdall] invalid event record received blockNum=62848864, eventId=2968357 (exp 2968357), chainId=137 (exp 137), time=2024-10-10 02:19:08.483928026 +0000 UTC (exp from 2024-10-10 02:41:37 +0000 UTC, to 2024-10-10 02:42:11 +0000 UTC)"
Oct 16 06:08:09 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:09.942] [3/9 BorHeimdall] Processing spans...    from=9822 to=9831
Oct 16 06:08:09 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:09.975] [3/9 BorHeimdall] Processing sync events... from=62848860 to=62913594
Oct 16 06:08:10 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [EROR] [10-16|06:08:10.030] Staged Sync                              err="[3/9 BorHeimdall] invalid event record received blockNum=62848864, eventId=2968357 (exp 2968357), chainId=137 (exp 137), time=2024-10-10 02:19:08.483928026 +0000 UTC (exp from 2024-10-10 02:41:37 +0000 UTC, to 2024-10-10 02:42:11 +0000 UTC)"
Oct 16 06:08:10 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:10.811] [3/9 BorHeimdall] Processing spans...    from=9822 to=9831
Oct 16 06:08:10 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:10.845] [3/9 BorHeimdall] Processing sync events... from=62848860 to=62913594
Oct 16 06:08:10 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [EROR] [10-16|06:08:10.900] Staged Sync                              err="[3/9 BorHeimdall] invalid event record received blockNum=62848864, eventId=2968357 (exp 2968357), chainId=137 (exp 137), time=2024-10-10 02:19:08.483928026 +0000 UTC (exp from 2024-10-10 02:41:37 +0000 UTC, to 2024-10-10 02:42:11 +0000 UTC)"

Oct 16 06:08:11 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:11.679] [3/9 BorHeimdall] Processing spans...    from=9822 to=9831
Oct 16 06:08:11 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [INFO] [10-16|06:08:11.714] [3/9 BorHeimdall] Processing sync events... from=62848860 to=62913594
Oct 16 06:08:11 rockx-mainnet-polygon-archive-mm-02 erigon[2209544]: [EROR] [10-16|06:08:11.775] Staged Sync                              err="[3/9 BorHeimdall] invalid event record received blockNum=62848864, eventId=2968357 (exp 2968357), chainId=137 (exp 137), time=2024-10-10 02:19:08.483928026 +0000 UTC (exp from 2024-10-10 02:41:37 +0000 UTC, to 2024-10-10 02:42:11 +0000 UTC)"

**Comment by AskAlexSharov** [comment] 2024-10-16 09:39
@zhy827827 try `git pull` - seems we fixed it recently

**Comment by zhy827827** [comment] 2024-10-16 09:45
erigon[2215408]: [EROR] [10-16|09:45:24.508] Staged Sync                              err="[3/9 BorHeimdall] invalid event record received blockNum=62848864, eventId=2968357 (exp 2968357), chainId=137 (exp 137), time=2024-10-10 02:19:08.483928026 +0000 UTC (exp from 2024-10-10 02:41:37 +0000 UTC, to 2024-10-10 02:42:11 +0000 UTC)"

see issues
