### ISSUE TITLE
Download snapshots stops at progress="99.90% 3.6TB/3.6TB

### ISSUE THREAD

**Issue by directsyndikat** [erigontech/erigon#11475] opened 2024-08-04 12:02 UTC
System information
8 TB NVME
256GB DDR5
arm CPU 80 cores

Erigon version: Erigon3

OS & Version: Ubunto 22.4

Commit hash: 

Erigon Command (with flags/config):
./build/bin/erigon 
--chain=bor-mainnet 
--bor.heimdall=https://heimdall-api.polygon.technology/ 
--http.api=debug,eth,net,web3,bor,trace 
--ws=true 
--ws.port=8555 
--db.read.concurrency=8000 
--rpc.batch.concurrency=160 
--sync.loop.block.limit=40000 
--batchSize=8G 
--torrent.download.rate=512mb

Chain/Network: 
Polygon Archive
#### Expected behaviour
Download snapshots > sync

#### Actual behaviour
```
INFO[08-04|13:55:18.062] [1/9 Snapshots] download                 progress="99.90% 3.6TB/3.6TB" time-left=999hrs:99m total-time=12m0s download=0B/s upload=0B/s peers=2 files=1351 metadata=1347/1351 connections=2 alloc=3.3GB sys=15.1GB
INFO[08-04|13:55:32.252] [snapshots] no metadata yet              files=4 list=domain/v1-storage.2688-2752.kv,domain/v1-accounts.2688-2752.kv,domain/v1-commitment.2688-2752.kv,domain/v1-code.2688-2752.kv
INFO[08-04|13:55:38.061] [1/9 Snapshots] download                 progress="99.90% 3.6TB/3.6TB" time-left=999hrs:99m total-time=12m20s download=0B/s upload=0B/s peers=3 files=1351 metadata=1347/1351 connections=3 alloc=2.5GB sys=15.1GB
INFO[08-04|13:55:52.250] [snapshots] no metadata yet              files=4 list=domain/v1-accounts.2688-2752.kv,domain/v1-commitment.2688-2752.kv,domain/v1-code.2688-2752.kv,domain/v1-storage.2688-2752.kv
INFO[08-04|13:55:58.061] [1/9 Snapshots] download                 progress="99.90% 3.6TB/3.6TB" time-left=999hrs:99m total-time=12m40s download=0B/s upload=0B/s peers=6 files=1351 metadata=1347/1351 connections=6 alloc=3.6GB sys=15.1GB
INFO[08-04|13:56:12.249] [snapshots] no metadata yet              files=4 list=domain/v1-storage.2688-2752.kv,domain/v1-accounts.2688-2752.kv,domain/v1-commitment.2688-2752.kv,domain/v1-code.2688-2752.kv
INFO[08-04|13:56:18.063] [1/9 Snapshots] download                 progress="99.90% 3.6TB/3.6TB" time-left=999hrs:99m total-time=13m0s download=0B/s upload=0B/s peers=5 files=1351 metadata=1347/1351 connections=5 alloc=4.5GB sys=15.1GB
```

#### Steps to reproduce the behaviour
Use flags on a clean machine, download always stops at 99.90%

**Comment by awskii** [comment] 2024-08-08 08:56
Hello, that still could happen sometimes due to some bugs in torrent lib we're fixing causing stalling download. Please restart erigon couple of times (without need to delete something) which should succeed.

**Comment by mh0lt** [comment] 2024-08-09 09:43
The issue here is that these files have no metadata:
files=4 list=domain/v1-storage.2688-2752.kv,domain/v1-accounts.2688-2752.kv,domain/v1-commitment.2688-2752.kv,domain/v1-code.2688-2752.kv

This is not a bug in the torrent lib it is caused by missing files/.torrent files in the distribution.

**Comment by michelemodolo** [comment] 2024-08-09 10:42
`domain/*.2688*` don't exist on the snapshotter node any longer because they were merged to bigger files.
So `domain/*.2688*` are no longer present in the relevant manifest.txt (and of course they are not present in the bor-mainnet.toml either)

HOWEVER...

`domain/*.2688*` STILL exist in the public bucket (with TTL set to 8 weeks after they disappeared from the snapshotter node)

So `domain/*.2688*` _are still available to be downloaded_ from the relevant (in this case bor-mainnet) bucket.

Please note that `domain/*.2688*` files were stored in the bucket on the 5th of July 2024 so they will be removed from the bucket on the 5th of September 2024 (if needed, I can set a TTL longer than 8 weeks).

**Comment by mh0lt** [comment] 2024-08-09 12:14
https://github.com/directsyndikat which version of e3 are you running alpha1 or alpha2 ?

**Comment by SLoeuillet** [comment] 2024-08-19 07:54
Got the same thing happening with current main : git_tag=v3.0.0-alpha2-94-g12ebd14c56

Been stuck at 99.90% for days, retrying with new HEAD every day with no luck

```
Aug 19 07:53:30 polygon01-mainnet-ovh erigon[498344]: [INFO] [08-19|07:53:30.360] [snapshots] no metadata yet              files=30 list=v1-059941-059942-transactions.seg,v1-059942-059943-transactions.seg,domain/v1-code.2816-2818.kv,v1-059936-059937-transactions.seg,idx/v1-accounts.2816-2818.ef,...
Aug 19 07:53:34 polygon01-mainnet-ovh erigon[498344]: [INFO] [08-19|07:53:34.126] [1/9 OtterSync] download                 progress="99.90% 3.8TB/3.8TB" time-left=999hrs:99m total-time=11m40s download=0B/s flush=0B/s hash=0B/s complete=0B/s upload=0B/s peers=0 files=1479 metadata=1449/1479 connections=0 alloc=5.9GB sys=10.6GB
```

I never was on a1. Started with a2 and encountered that issue

**Comment by SLoeuillet** [comment] 2024-08-19 09:49
Removed everything but snapshots directory , then

```
Aug 19 09:45:19 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:19.075] [1/9 OtterSync] downloading header-chain progress="99.90% 3.8TB/3.8TB" time-left=999hrs:99m total-time=18m0s download=0B/s flush=0B/s hash=3.4GB/s complete=0B/s upload=0B/s peers=0 files=1449 metadata=1449/1449 connections=0 alloc=8.6GB sys=14.3GB
Aug 19 09:45:27 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:27.296] [mem] memory stats                       Rss=55.3GB Size=0B Pss=55.3GB SharedClean=2.9MB SharedDirty=0B PrivateClean=43.7GB PrivateDirty=11.6GB Referenced=32.5GB Anonymous=11.6GB Swap=0B alloc=9.0GB sys=14.3GB
Aug 19 09:45:39 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:39.070] [1/9 OtterSync] header-chain download finished time=18m20.00026614s
Aug 19 09:45:43 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:43.140] [1/9 OtterSync] Requesting downloads
Aug 19 09:45:43 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:43.217] [snapshots] no metadata yet              files=30 list=v1-059930-059931-transactions.seg,v1-059940-059941-transactions.seg,history/v1-code.2816-2818.v,v1-059938-059939-transactions.seg,v1-059932-059933-transactions.seg,...
Aug 19 09:45:58 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:58.170] [snapshots] no metadata yet              files=30 list=v1-059932-059933-transactions.seg,idx/v1-logtopics.2816-2818.ef,v1-059931-059932-transactions.seg,v1-059920-059930-transactions.seg,idx/v1-tracesto.2816-2818.ef,...
Aug 19 09:46:03 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:46:03.217] [1/9 OtterSync] download                 progress="99.90% 3.8TB/3.8TB" time-left=999hrs:99m total-time=20s download=0B/s flush=0B/s hash=46.3MB/s complete=0B/s upload=0B/s peers=0 files=1479 metadata=1449/1479 connections=0 alloc=10.2GB sys=14.3GB
```

**Comment by SLoeuillet** [comment] 2024-08-19 09:56
should I remove those 30 files without metadata from snapshots/preverified.toml file ?
[11:55]
(those are referenced in that file)
[11:55]
I did remove 2 of them from it, and now : no metadata yet              files=28

**Comment by michelemodolo** [comment] 2024-08-19 10:31
> Removed everything but snapshots directory , then
> 
> ```
> Aug 19 09:45:19 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:19.075] [1/9 OtterSync] downloading header-chain progress="99.90% 3.8TB/3.8TB" time-left=999hrs:99m total-time=18m0s download=0B/s flush=0B/s hash=3.4GB/s complete=0B/s upload=0B/s peers=0 files=1449 metadata=1449/1449 connections=0 alloc=8.6GB sys=14.3GB
> Aug 19 09:45:27 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:27.296] [mem] memory stats                       Rss=55.3GB Size=0B Pss=55.3GB SharedClean=2.9MB SharedDirty=0B PrivateClean=43.7GB PrivateDirty=11.6GB Referenced=32.5GB Anonymous=11.6GB Swap=0B alloc=9.0GB sys=14.3GB
> Aug 19 09:45:39 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:39.070] [1/9 OtterSync] header-chain download finished time=18m20.00026614s
> Aug 19 09:45:43 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:43.140] [1/9 OtterSync] Requesting downloads
> Aug 19 09:45:43 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:43.217] [snapshots] no metadata yet              files=30 list=v1-059930-059931-transactions.seg,v1-059940-059941-transactions.seg,history/v1-code.2816-2818.v,v1-059938-059939-transactions.seg,v1-059932-059933-transactions.seg,...
> Aug 19 09:45:58 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:45:58.170] [snapshots] no metadata yet              files=30 list=v1-059932-059933-transactions.seg,idx/v1-logtopics.2816-2818.ef,v1-059931-059932-transactions.seg,v1-059920-059930-transactions.seg,idx/v1-tracesto.2816-2818.ef,...
> Aug 19 09:46:03 polygon01-mainnet-ovh erigon[502717]: [INFO] [08-19|09:46:03.217] [1/9 OtterSync] download                 progress="99.90% 3.8TB/3.8TB" time-left=999hrs:99m total-time=20s download=0B/s flush=0B/s hash=46.3MB/s complete=0B/s upload=0B/s peers=0 files=1479 metadata=1449/1479 connections=0 alloc=10.2GB sys=14.3GB
> ```
> 
> Note that at "downloading header chain" step, there were metadata 1449/1449
> 
> Then once over, the infamous 30 files without metadata came back

All the files mentioned in the log here above are present in both the current bor-mainnet.toml (which is reflected on the preverified.toml file) AND in the bucket. So this doesn't seem to be an infrastructure-related issue. 

What could be the downloader looking for @mh0lt ?

**Comment by SLoeuillet** [comment] 2024-08-19 11:07
Once all 30 files with no metadata were removed from snapshots/preverified.toml file, it went to "[1/9 OtterSync] Indexing"

**Comment by SLoeuillet** [comment] 2024-08-19 11:09
@michelemodolo I only kept snapshots/ directory.  But it includes snapshots/preverified.toml file which contains file which are not seeded anymore

**Comment by SLoeuillet** [comment] 2024-08-19 11:17
eth/backend.go loadSnapshotsEitherFromDiskIfNeeded

If it founds a local/existing snapshots/preverified.toml file, it uses it, even if it is outdated compared to the online reference. So if it contains file which are not seeded anymore, it won't be able to download them and would stay stuck forever (no metadata for those files)

**Comment by SLoeuillet** [comment] 2024-08-19 11:18
So until this is fixed, the workaround should be to remove that local file, that would download a newer one

**Comment by michelemodolo** [comment] 2024-08-19 11:39
> eth/backend.go loadSnapshotsEitherFromDiskIfNeeded
> 
> If it founds a local/existing snapshots/preverified.toml file, it uses it, even if it is outdated compared to the online reference. So if it contains file which are not seeded anymore, it won't be able to download them and would stay stuck forever (no metadata for those files)

True. However in your case, as mentioned [here](https://github.com/erigontech/erigon/issues/11475#issuecomment-2296244827),  "the files without metadata" were still seeded because they were present in both the current bor-mainnet.toml (which is reflected on the preverified.toml file) AND in the relevant webseed (note that I only checked all the files reported in your log **excerpt**) so I guess that the downloader was trying to retrieve those files from some wrong place (maybe some wrong webseeds). 

Your workaround fixed the problem at the expense of performance (your node didn't download recent files because of the issue with metadata), yet your machine high specs would certainly cope with that.

**Comment by mh0lt** [comment] 2024-08-30 12:03
I have closed this issue because I think the specific issue has now been fixed, and we're updated the code to detect this so its clearer what is happening. 

However underlying issues with no metadata are due to the alpha process which means we're changing files more frequently due to underlying fixed.  

In general 'no metadata' means file not found in torrent.

**Closed by mh0lt** 2024-08-30 12:03 UTC
Labels: priority:high
