### ISSUE TITLE
Implement pectra-devnet-4 changes

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#12106] opened 2024-09-26 14:14 UTC
https://notes.ethereum.org/@ethpandaops/pectra-devnet-4

- [x] <del>  EIP-7251 address update: Done - https://github.com/ethereum/EIPs/pull/8889 </del>
- [x] <del> Block body requests header update: Abandoned - https://github.com/ethereum/EIPs/pull/8908 </del>
- [x] Change to Engine API and block body for requests (flattening): TODO - https://github.com/ethereum/execution-apis/pull/591
- [x] Change deposit reqs to flat encoding: Done, needs changes - https://github.com/ethereum/EIPs/pull/8856
- [x] Change withdrawal reqs to flat encoding: In Progress - https://github.com/ethereum/EIPs/pull/8855
- [x] Change reqs hash to flat hash: Done, needs changes - https://github.com/ethereum/EIPs/pull/8854
- [x] Change consolidation reqs to flat encoding: Done, needs changes - https://github.com/ethereum/EIPs/pull/8857
- [x] Updated opaque requests: TODO - https://github.com/ethereum/EIPs/pull/8924
- [x] Change requests serialization: TODO - https://github.com/ethereum/EIPs/pull/8949
- [x] Update 7002 contract addr after logic update: Done - https://github.com/ethereum/EIPs/pull/8934
- [x] Update 7251 contract addr after logic update: Done - https://github.com/ethereum/EIPs/pull/8934
- [x] Implement changes for EIP-7702 and fix tests: Pending - https://github.com/ethereum/EIPs/pull/8948, https://github.com/ethereum/EIPs/pull/8929, https://github.com/ethereum/EIPs/pull/8938, https://github.com/ethereum/EIPs/pull/8845

v1.0.1 release of pectra-devnet-4 tests release at https://github.com/ethereum/execution-spec-tests already merged.

**Comment by somnathb1** [comment] 2024-09-30 07:34
Priority high here means importance, not all EIPs in the list have been merged/finalized yet for pectra-devnet-4. The issue is expected to remain open for some time till the EIPs are finalized. The code changes will be accumulated over multiple PRs referencing this issue.

**Closed** 2024-11-06 12:02 UTC
Labels: pectra, imp1
