### ISSUE TITLE
 Rejected header marked as bad 

### ISSUE THREAD

**Issue by directsyndikat** [erigontech/erigon#11473] opened 2024-08-03 16:52 UTC
Currently facing the following:

The node itself has been running for quite some days without issues up until today.
It keeps spamming the following logs, restarting the node does not seem to work.

From reading previous issues i attempt to 
`integration state_stages --unwind=10 --datadir="/root/erigon/.local/share/erigon/bor-mainnet"  --chain="bor-mainnet"`
However it does not recognize 'integration'  

```



WARN[08-03|18:46:48.726] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.728] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.730] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.732] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.734] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.737] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.746] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.748] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.750] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.755] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.756] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.772] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.784] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.786] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.789] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.791] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.796] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.799] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
WARN[08-03|18:46:48.805] [downloader] Rejected header marked as bad hash=0xbfef129a747e5861405e2aceef1d76c7b8bf42d3aadde35b62a4cabf6ff2a5ad height=60137759
```

**Comment by directsyndikat** [comment] 2024-08-05 15:45
I am running [erigon_3.0.0-alpha1_linux_arm64.tar.gz]
seems like files such as history/v1-accounts.2688-2752.v' = 'fbe6a3a701cda8ff6adfc4a8b33f9e1bb2b1781b' are not present in the manifest file

**Comment by yperbasis** [comment] 2024-08-09 08:55
Does this still happen with [v3.0.0-alpha2](https://github.com/erigontech/erigon/releases/tag/v3.0.0-alpha2)?

**Comment by AskAlexSharov** [comment] 2024-08-24 11:50
yes. and it's duplicate of https://github.com/erigontech/erigon/issues/11387

**Closed** 2024-10-25 16:17 UTC
Labels: imp2, erigon3
